apiVersion: v1
kind: Service
metadata:
  name: international-audit-streamlit
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
     - 115.117.115.6/32
     - 52.172.178.185/32
     - 20.198.125.237/32
  ports:
    - name: http
      port: 443
      targetPort: 443
    - name: https
      port: 80
      targetPort: 80
  selector:
    app: international-audit-streamlit

