apiVersion: v1
kind: Service
metadata:
  name: stp-streamlit
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
     - 115.117.115.6/32
     - 52.172.178.185/32
     - 20.198.125.237/32
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: https
      port: 8001
      targetPort: 8001
  selector:
    app: stp-streamlit

