# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
port: 8000
image:
  repository: vidaldevacr.azurecr.io/FAA-International
  tag: latest

serviceName: faa-international-streamlit
releaseName: faa-international-streamlit

# KeyvaultName : insightrx-automation
# KeyvaultName_common : insightrx-common

namespace: insightrx-dev
label: faa-international-streamlit
TargetPort: 8000
containerName: faa-international-streamlit
containerPort: 8000

tolerations:  
- effect: NoSchedule
  key: appType
  operator: Equal
  value: nodejs_py

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appType
          operator: In
          values:
          - nodejs_py
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            -  faa-international-streamlit
        topologyKey: "kubernetes.io/hostname"
          
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 600m
    memory: 1000Mi
ServicePort: 80
name: faa-international-streamlit
podName: international-streamlit
environment: dev

# APP:
#   MONGO_DB: stp-uat