# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
port: 8000
image:
  repository: vidalprodacr.azurecr.io/InternationalAudit
  tag: latest

serviceName: international-audit-streamlit
releaseName: international-audit-streamlit

# KeyvaultName : insightrx-common
# KeyvaultName_common : insightrx-common

namespace: insightrx
label: international-audit-streamlit
TargetPort: 8000
containerName: international-audit-streamlit
containerPort: 8000

tolerations:  
- effect: NoSchedule
  key: appType
  operator: Equal
  value: mlprod

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: appType
          operator: In
          values:
          - mlprod
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            -  international-audit-streamlit
        topologyKey: "kubernetes.io/hostname"
          

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 800m
    memory: 1000Mi
ServicePort: 80
name: international-audit-streamlit
podName: international-streamlit
environment: prod

# APP:
#   MONGO_DB: stp